import os
import rtconfig

# Check SDK 
SIFLI_SDK = os.getenv('SIFLI_SDK')
if not SIFLI_SDK:
    print("Please run set_env.bat in root folder of SIFLI SDK to set environment.")
    exit()
from building import *

# Prepare environment.
PrepareEnv()


################################## change rtconfig.xxx to customize build ########################################

skip_child_projects = os.getenv('SIFLI_SKIP_CHILD_PROJECTS') == '1'

if not skip_child_projects:
    # Add bootloader project
    AddBootLoader(SIFLI_SDK,rtconfig.CHIP)

    # Add LCPU project
    AddLCPU(SIFLI_SDK,rtconfig.CHIP,"../../src/lcpu_img.c")

# Set default compile options
SifliEnv()

if skip_child_projects and getattr(rtconfig, 'LINK_SCRIPT_SRC', None) is None:
    board_link_script = os.path.join(GetBoardName(), 'link')
    if os.path.exists(board_link_script + '.lds'):
        rtconfig.LINK_SCRIPT_SRC = board_link_script
    else:
        rtconfig.LINK_SCRIPT_SRC = os.path.join(rtconfig.OUTPUT_DIR, 'link_copy')
    if getattr(rtconfig, 'LINK_SCRIPT', None) is None:
        rtconfig.LINK_SCRIPT = os.path.join(rtconfig.OUTPUT_DIR, 'link_copy')

TARGET = rtconfig.OUTPUT_DIR + rtconfig.TARGET_NAME + '.' + rtconfig.TARGET_EXT
env = Environment(tools = ['mingw'],
    AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
    CC = rtconfig.CC, CFLAGS = rtconfig.CFLAGS,
    CXX = rtconfig.CXX, CXXFLAGS = rtconfig.CXXFLAGS,
    AR = rtconfig.AR, ARFLAGS = '-rc',
    LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)
env.PrependENVPath('PATH', rtconfig.EXEC_PATH)
   
# Prepare building environment
objs = PrepareBuilding(env)

# Build application.
DoBuilding(TARGET, objs)

if not skip_child_projects:
    # Add DFU_PAN OTA
    AddDFU_PAN(SIFLI_SDK)

    # Add flash table buld.
    AddFTAB(SIFLI_SDK,rtconfig.CHIP)

# Generate download .bat script
GenDownloadScript(env)
