// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: Smart_Gadget
#ifndef XIAOZHI_UI_EVENTS_H
#define XIAOZHI_UI_EVENTS_H

/* Reserved for future UI event declarations. */

#endif
#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
