#ifndef XIAOZHI_UI_TYPES_H
#define XIAOZHI_UI_TYPES_H

typedef enum
{
    UI_SCREEN_NONE = 0,
    UI_SCREEN_HOME,
    UI_SCREEN_STANDBY,
    UI_SCREEN_READING_LIST,
    UI_SCREEN_READING_DETAIL,
    UI_SCREEN_PET,
    UI_SCREEN_PET_RULES,
    UI_SCREEN_AI_DOU,
    UI_SCREEN_TIME_MANAGE,
    UI_SCREEN_POMODORO,
    UI_SCREEN_DATETIME,
    UI_SCREEN_WEATHER,
    UI_SCREEN_CALENDAR,
    UI_SCREEN_STATUS_DETAIL,
    UI_SCREEN_RECORDER,
    UI_SCREEN_RECORD_LIST,
    UI_SCREEN_MUSIC_LIST,
    UI_SCREEN_MUSIC_PLAYER,
    UI_SCREEN_SETTINGS,
    UI_SCREEN_BRIGHTNESS,
    UI_SCREEN_LANGUAGE,
    UI_SCREEN_BLUETOOTH_CONFIG,
    UI_SCREEN_WALLPAPER,
    UI_SCREEN_COUNT
} ui_screen_id_t;

enum
{
    UI_FIGMA_WIDTH = 528,
    UI_FIGMA_HEIGHT = 792
};

#endif
