import os
from building import *

cwd = GetCurrentDir()
src = [
    os.path.join(cwd, 'app_buttons.c'),
    os.path.join(cwd, 'app_watchdog.c'),
    os.path.join(cwd, 'app_audio_mem.c'),
    os.path.join(cwd, 'bt_mem.c'),
    os.path.join(cwd, 'main.c'),
    os.path.join(cwd, 'aw32001_debug.c'),
    os.path.join(cwd, 'bq27220_monitor.c'),
    os.path.join(cwd, 'audio_manager.c'),
    os.path.join(cwd, 'music_service.c'),
    os.path.join(cwd, 'sleep_manager.c'),
    os.path.join(cwd, 'petgame_reducer.c'),
    os.path.join(cwd, 'petgame_storage.c'),
    os.path.join(cwd, 'config', 'app_config.c'),
    os.path.join(cwd, 'config', 'app_config_storage.c'),
    os.path.join(cwd, 'network', 'net_manager.c'),
    os.path.join(cwd, 'network', 'net_http_lock.c'),
    os.path.join(cwd, 'network', 'network_mem.c'),
    os.path.join(cwd, 'ui', 'home_screen.c'),
    os.path.join(cwd, 'ui', 'ui.c'),
    os.path.join(cwd, 'ui', 'ui_i18n.c'),
    os.path.join(cwd, 'ui', 'ui_dispatch.c'),
    os.path.join(cwd, 'ui', 'ui_font_manager.c'),
    os.path.join(cwd, 'ui', 'ui_helpers.c'),
    os.path.join(cwd, 'ui', 'ui_status_bar.c'),
    os.path.join(cwd, 'ui', 'ui_runtime_adapter.c'),
    os.path.join(cwd, 'reading', 'reading_epub.c'),
    os.path.join(cwd, 'reading', 'reading_state.c'),
]
src.extend(Glob(os.path.join(cwd, 'ui', 'screens', '*.c')))

cpppath = [
    cwd,
    os.path.join(cwd, 'board'),
    os.path.join(cwd, 'config'),
    os.path.join(cwd, 'reading'),
    os.path.join(cwd, 'network'),
    os.path.join(cwd, 'ui'),
    os.path.join(cwd, 'ui', 'fonts'),
    os.path.join(cwd, 'ui', 'screens'),
    os.path.join(cwd, 'xiaozhi'),
    os.path.join(cwd, 'xiaozhi', 'kws'),
    os.path.join(cwd, '..', '..', 'sdk', 'customer', 'peripherals', '4g', 'cat1_modem'),
    os.path.join(cwd, '..', '..', 'sdk', 'rtos', 'rtthread', 'components', 'net', 'at', 'include'),
    os.path.join(cwd, '..', '..', 'sdk', 'middleware', 'include'),
    os.path.join(cwd, '..', '..', 'sdk', 'middleware', 'audio', 'include'),
    os.path.join(cwd, '..', '..', 'sdk', 'middleware', 'audio', 'audio_port'),
]

group = DefineGroup('Applications',
                    src,
                    depend=[''],
                    CPPPATH=cpppath)

# Load xiaozhi module group
xiaozhi_group = SConscript(os.path.join(cwd, 'xiaozhi', 'SConscript'))
if xiaozhi_group:
    group = group + xiaozhi_group

Return('group')
